[package]
name = "ariel-os-native"
version = "0.2.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true, optional = true }
embassy-executor = { workspace = true, default-features = false }
embassy-time = { workspace = true, default-features = false, features = [
  "std",
] }
embedded-hal-async = { workspace = true }
ariel-os-buildinfo = { workspace = true }
ariel-os-debug = { workspace = true, features = ["std"] }
ariel-os-embassy-common = { workspace = true }
ariel-os-random = { workspace = true, optional = true }
rand = { workspace = true, default-features = false, optional = true, features = [
  "os_rng",
] }
sha2 = { version = "0.10.8", default-features = false }

[features]
## Enables GPIO interrupt support.
external-interrupts = ["ariel-os-embassy-common/external-interrupts"]

## Enables seeding the random number generator from hardware.
hwrng = ["dep:ariel-os-random", "dep:rand"]

## Enables I2C support.
i2c = ["ariel-os-embassy-common/i2c"]

## Enables SPI support.
spi = ["ariel-os-embassy-common/spi"]

## Enables storage support.
storage = ["dep:embassy-embedded-hal"]

## Enables USB support.
usb = []

## Enables defmt support.
defmt = ["dep:defmt"]
