//! Driver for the sensor used over I2C.

use ariel_os_debug::log::debug;
use ariel_os_embassy::api::time::Timer;
use ariel_os_hal::i2c::controller::I2cDevice;
use ariel_os_sensors::{
    Category, Label, MeasurementUnit, Sensor,
    sensor::{
        Mode as SensorMode, ReadingChannel, ReadingChannels, ReadingError, ReadingWaiter, Sample,
        SampleMetadata, Samples, SetModeError, State, TriggerMeasurementError,
    },
};
use ariel_os_sensors_utils::{SensorSignaling, StateAtomic};
use embassy_sync::{
    blocking_mutex::raw::CriticalSectionRawMutex, mutex::Mutex, once_lock::OnceLock,
};
use embedded_hal_async::i2c::I2c;
use portable_atomic::{AtomicU8, Ordering};

use crate::{
    AccelFullScale, AccelMode, AccelOdr, GyroFullScale, GyroMode, GyroOdr, PART_NUMBER, Register,
};

/// I2C address of the sensor device.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Default)]
pub enum I2cAddress {
    /// The SA0 pin is pulled low.
    Sa0Gnd = 0b1101010,
    #[default]
    /// The SA0 pin is pulled high.
    Sa0Vdd = 0b1101011,
}

/// Configuration of the sensor driver and device.
#[derive(Debug, Default)]
#[non_exhaustive]
pub struct Config {
    /// I2C address to use.
    pub address: I2cAddress,
}

ariel_os_embassy::hal::define_peripherals!(
    /// Peripherals required by the sensor driver.
    Peripherals {}
);

/// Driver to use an LSM6DSV16X over I2C.
pub struct Lsm6dsv16x {
    state: StateAtomic,
    label: Option<&'static str>,
    i2c: OnceLock<Mutex<CriticalSectionRawMutex, I2cDevice>>,
    address: AtomicU8,
    signaling: SensorSignaling,
}

impl Lsm6dsv16x {
    /// Creates an uninitialized driver.
    #[expect(clippy::new_without_default)]
    #[must_use]
    pub const fn new(label: Option<&'static str>) -> Self {
        Self {
            state: StateAtomic::new(State::Uninitialized),
            label,
            i2c: OnceLock::new(),
            address: AtomicU8::new(I2cAddress::Sa0Vdd as u8),
            signaling: SensorSignaling::new(),
        }
    }

    /// Initializes the driver.
    pub async fn init(
        &'static self,
        _peripherals: Peripherals,
        i2c_device: I2cDevice,
        config: Config,
    ) {
        if !self.i2c.is_set() {
            let i2c_device = Mutex::new(i2c_device);

            self.address.store(config.address as u8, Ordering::Release);

            let res = i2c_device
                .lock()
                .await
                .write(
                    config.address as u8,
                    &[Register::Ctrl3 as u8, crate::SW_RESET_BITS],
                )
                .await;

            if res.is_err() {
                return;
            }

            let _ = self.i2c.init(i2c_device);

            self.state.set(State::Enabled);
            debug!("{} enabled", PART_NUMBER);
        }
    }

    /// Listens for measurement requests generated by [`Lsm6dsv16x::trigger_measurement()`], and
    /// responds to them.
    /// This should be called before [`Lsm6dsv16x::wait_for_reading()`], as it will otherwise delay
    /// the response.
    ///
    /// # Note
    ///
    /// [`Lsm6dsv16x::init()`] needs to be called and `await`ed before calling this method.
    pub async fn run(&'static self) -> ! {
        loop {
            self.signaling.wait_for_trigger().await;

            if self.state.get() == State::Sleeping {
                let _ = self.power_down().await;
                continue;
            }

            match self.measure().await {
                Ok(samples) => self.signaling.signal_reading(samples).await,
                Err(err) => self.signaling.signal_reading_err(err).await,
            }
        }
    }

    async fn measure(&'static self) -> Result<Samples, ReadingError> {
        let mut i2c = self.i2c.get().await.lock().await;
        let address = self.address.load(Ordering::Acquire);

        // Trigger acceleration and gyroscope measurement.
        let ctrl1 = AccelMode::HighPerformance as u8 | AccelOdr::_1_92kHz as u8;
        let ctrl2 = GyroMode::HighPerformance as u8 | GyroOdr::_1_92kHz as u8;
        i2c.write(address, &[Register::Ctrl1 as u8, ctrl1, ctrl2])
            .await
            .map_err(|_| ReadingError::SensorAccess)?;

        // Wait for the measurements.
        loop {
            let mut buf = [0u8];
            i2c.write_read(address, &[Register::StatusReg as u8], &mut buf)
                .await
                .map_err(|_| ReadingError::SensorAccess)?;

            // New data available.
            let mask = crate::GDA_BITS | crate::XLDA_BITS;
            if buf[0] & mask == mask {
                break;
            }

            // TODO: configuration
            Timer::after_millis(10).await;
        }

        // Read all angular velocity and acceleration registers.
        let mut buf = [0u8; 2 * 6];
        i2c.write_read(address, &[Register::OutxLG as u8], &mut buf)
            .await
            .map_err(|_| ReadingError::SensorAccess)?;

        let accel_sensitivity = AccelFullScale::_2g.as_sensitivity_thousandths();
        let accel_x =
            i32::from(i16::from_be_bytes([buf[7], buf[6]])) * i32::from(accel_sensitivity);
        let accel_y =
            i32::from(i16::from_be_bytes([buf[9], buf[8]])) * i32::from(accel_sensitivity);
        let accel_z =
            i32::from(i16::from_be_bytes([buf[11], buf[10]])) * i32::from(accel_sensitivity);

        // `LA_TyOff` from Table 3 of the datasheet.
        let accel_accuracy = SampleMetadata::SymmetricalError {
            deviation: 12, // TODO: this could possibly be refined by taking into account `An` as well.
            bias: 0,
            scaling: -3,
        };

        let gyro_scale = GyroFullScale::_125dps.as_sensitivity_hundredths();
        let gyro_x = i32::from(i16::from_be_bytes([buf[1], buf[0]])) * i32::from(gyro_scale);
        let gyro_y = i32::from(i16::from_be_bytes([buf[3], buf[2]])) * i32::from(gyro_scale);
        let gyro_z = i32::from(i16::from_be_bytes([buf[5], buf[4]])) * i32::from(gyro_scale);

        // `G_TyOff` from Table 3 of the datasheet.
        let gyro_accuracy = SampleMetadata::SymmetricalError {
            deviation: 1, // TODO: this could possibly be refined by taking into account `Rn` as well.
            bias: 0,
            scaling: 0,
        };

        let samples = Samples::from_6(
            self,
            [
                Sample::new(accel_x, accel_accuracy),
                Sample::new(accel_y, accel_accuracy),
                Sample::new(accel_z, accel_accuracy),
                Sample::new(gyro_x, gyro_accuracy),
                Sample::new(gyro_y, gyro_accuracy),
                Sample::new(gyro_z, gyro_accuracy),
            ],
        );

        Ok(samples)
    }

    // TODO: test this
    async fn power_down(&self) -> Result<(), ReadingError> {
        let accel_power_down = AccelMode::HighPerformance as u8 | AccelOdr::PowerDown as u8;
        let gyro_power_down = GyroMode::Sleep as u8 | GyroOdr::PowerDown as u8;

        let mut i2c = self.i2c.get().await.lock().await;
        let address = self.address.load(Ordering::Acquire);
        i2c.write(
            address,
            &[Register::Ctrl1 as u8, accel_power_down, gyro_power_down],
        )
        .await
        .map_err(|_| ReadingError::SensorAccess)
    }
}

impl Sensor for Lsm6dsv16x {
    fn trigger_measurement(&self) -> Result<(), TriggerMeasurementError> {
        if self.state.get() != State::Enabled {
            return Err(TriggerMeasurementError::NonEnabled);
        }

        self.signaling.trigger_measurement();

        Ok(())
    }

    fn wait_for_reading(&'static self) -> ReadingWaiter {
        if self.state.get() != State::Enabled {
            return ReadingWaiter::Err(ReadingError::NonEnabled);
        }

        self.signaling.wait_for_reading()
    }

    /// Sets the sensor driver mode and returns the previous state.
    /// Allows to put the sensor device to sleep.
    fn set_mode(&self, mode: SensorMode) -> Result<State, SetModeError> {
        let new_state = self.state.set_mode(mode);

        if new_state == State::Uninitialized {
            Err(SetModeError::Uninitialized)
        } else {
            // Trigger the listening loop.
            self.signaling.trigger_measurement();
            Ok(new_state)
        }
    }

    fn state(&self) -> State {
        self.state.get()
    }

    fn categories(&self) -> &'static [Category] {
        &[
            Category::Accelerometer,
            Category::AccelerometerGyroscope,
            Category::Gyroscope,
        ]
    }

    fn reading_channels(&self) -> ReadingChannels {
        ReadingChannels::from([
            ReadingChannel::new(Label::AccelerationX, -6, MeasurementUnit::AccelG),
            ReadingChannel::new(Label::AccelerationY, -6, MeasurementUnit::AccelG),
            ReadingChannel::new(Label::AccelerationZ, -6, MeasurementUnit::AccelG),
            ReadingChannel::new(
                Label::AngularVelocityX,
                -5,
                MeasurementUnit::DegreePerSecond,
            ),
            ReadingChannel::new(
                Label::AngularVelocityY,
                -5,
                MeasurementUnit::DegreePerSecond,
            ),
            ReadingChannel::new(
                Label::AngularVelocityZ,
                -5,
                MeasurementUnit::DegreePerSecond,
            ),
        ])
    }

    fn label(&self) -> Option<&'static str> {
        self.label
    }

    fn display_name(&self) -> Option<&'static str> {
        Some("6-axis IMU")
    }

    fn part_number(&self) -> Option<&'static str> {
        Some(PART_NUMBER)
    }

    fn version(&self) -> u8 {
        0
    }
}
