[package]
name = "ariel-os-utils"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
const-str = { workspace = true }
const_panic = { workspace = true }

[lints]
workspace = true
