[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"     # Optimize for size even in debug builds

[profile.release]
incremental = false
codegen-units = 1
debug = true        # Required for defmt
lto = false
opt-level = "s"

[profile.release.package.esp-wifi]
opt-level = 3

[patch.crates-io]
# ariel-os embassy forks

# branch = "embassy-embedded-hal-v0.3.0+ariel-os",
embassy-embedded-hal = { git = "https://github.com/ariel-os/embassy", rev = "21147bdceb85f55e375973f30e47c17036063689" }
# branch = "embassy-executor-v0.7.0+04.04.25+ariel-os",
embassy-executor = { git = "https://github.com/ariel-os/embassy", rev = "b552a87578479a92b3027bd208c712445499589c" }
# branch = "embassy-executor-macros-v0.6.2+04.04.25"
embassy-executor-macros = { git = "https://github.com/ariel-os/embassy", rev = "1b08496e441cfd2b2e9660fe0cc589c3bc5f0824" }
# branch = "embassy-hal-internal-v0.2.0+ariel-os"
embassy-hal-internal = { git = "https://github.com/ariel-os/embassy", rev = "ed7d22c1881b64f9bdd2e69a5777b002279033a6" }
# branch = "embassy-nrf-v0.3.1+ariel-os"
embassy-nrf = { git = "https://github.com/ariel-os/embassy", rev = "1d258e63acc0a322ccea28786a4143115ba303b8" }
# branch = "embassy-rp-v0.4.0+ariel-os+trng-panic-fix"
embassy-rp = { git = "https://github.com/ariel-os/embassy", rev = "1dd58227a73efa8da2aef96aaccf17b8749b9f7b" }
# branch = "embassy-stm32-v0.2.0+ariel-os"
embassy-stm32 = { git = "https://github.com/ariel-os/embassy", rev = "90c8da09646d5fd97b7d416720688dcd3da1ecfb" }
# branch = "embassy-time-v0.4.0+ariel-os"
embassy-time = { git = "https://github.com/ariel-os/embassy", rev = "f9b4c8132b07ef696668005846ee2240a8f57573" }

# ariel-os esp-hal fork, using branch = "v0.23.1+ariel-os-threads"
esp-alloc = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }
esp-hal = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }
esp-hal-embassy = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }
esp-println = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }
esp-wifi = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }
xtensa-lx-rt = { git = "https://github.com/ariel-os/esp-hal", rev = "aa8d1995fc06eb5e6d04a2022ecf3679b4929e63" }

# patched to use portable-atomics <https://github.com/seanmonstar/try-lock/pull/11>
try-lock = { git = "https://github.com/seanmonstar/try-lock", rev = "45c39685b56a4dba1b71bdbbbe5f731c3c77dc50" }

# branch = "v0.6.2+ariel-os"
embedded-test = { git = "https://github.com/ariel-os/embedded-test", rev = "20642538eb4e6fa44b5f37723b07946c74b5c757" }
