[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s" # Optimize for size even in debug builds

[profile.release]
incremental = false
codegen-units = 1
debug = true # Required for defmt
lto = false
opt-level = "s"

[profile.release.package.esp-radio]
opt-level = 3

[patch.crates-io]
# ariel-os embassy forks

# branch = "embassy-hal-internal-v0.3.0+ariel-os"
embassy-hal-internal = { git = "https://github.com/kaspar030/embassy", rev = "0feffeb3c90748112a64c6570a39e1251311accb" }
# branch = "embassy-nrf-v0.7.0+ariel-os"
embassy-nrf = { git = "https://github.com/kaspar030/embassy", rev = "8576fc49be6538b794134aa6cd0b9b7163591f8b" }
# branch = "embassy-net-v0.7.1+ariel-os"
embassy-net = { git = "https://github.com/kaspar030/embassy", rev = "f88320aea64cf24026dd95ce3405ac23253b1117" }
# branch = "embassy-rp-v0.8.0+ariel-os"
embassy-rp = { git = "https://github.com/kaspar030/embassy", rev = "0314802282e112a47b4ccb303c0e7f09cf33df53" }
# branch = "embassy-stm32-v0.4.0+ariel-os"
embassy-stm32 = { git = "https://github.com/kaspar030/embassy", rev = "1b75c3d6e61a99a312e2d12f039fa6e76e9c3a9c" }

# ariel-os esp-hal fork, using branch = "esp-hal-20250930+ariel-os"
# esp-alloc = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
# esp-hal = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
# esp-println = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
# esp-radio = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
# esp-radio-rtos-driver = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
# xtensa-lx-rt = { git = "https://github.com/kaspar030/esp-hal", rev = "087a3a05d00810ea5fa3c67348836e5a71a44424" }
esp-alloc = { path = "/home/kaspar/src/esp-hal/esp-alloc" }
esp-bootloader-esp-idf = { path = "/home/kaspar/src/esp-hal/esp-bootloader-esp-idf" }
esp-hal = { path = "/home/kaspar/src/esp-hal/esp-hal" }
esp-println ={ path = "/home/kaspar/src/esp-hal/esp-println" }
esp-radio ={ path = "/home/kaspar/src/esp-hal/esp-radio" }
esp-radio-rtos-driver = { path = "/home/kaspar/src/esp-hal/esp-radio-rtos-driver" }
esp-rom-sys = { path = "/home/kaspar/src/esp-hal/esp-rom-sys" }
esp-sync = { path = "/home/kaspar/src/esp-hal/esp-sync" }
xtensa-lx-rt = { path = "/home/kaspar/src/esp-hal/xtensa-lx-rt" }

# branch = "v0.6.2+ariel-os"
embedded-test = { git = "https://github.com/ariel-os/embedded-test", rev = "20642538eb4e6fa44b5f37723b07946c74b5c757" }
