[workspace]
members = [
  "src/*",
  "src/riot-rs",
  "src/riot-rs-boards",
  "src/riot-rs-boards/lm3s6965evb",
  "src/riot-rs-boards/nrf52",
  "src/riot-rs-boards/nrf52840dk",
  "src/riot-rs-boards/nucleo-f401re",
  "src/riot-rs-chips",
  "src/lib/*",
  "examples/*",
]

exclude = ["src/lib"]

default-members = ["examples/hello-world"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
repository = "https://github.com/future-proof-iot/riot-rs"

[workspace.dependencies]
cfg-if = { version = "1.0.0" }
cortex-m = { version = "0.7", default-features = false, features = [ "inline-asm" ] }
cortex-m-rt = { version = "0.7" }
cortex-m-semihosting = { version = "0.5" }
critical-section = { version = "1.1.2" }

embassy-executor = { version = "0.5", default-features = false }
embassy-net = { version = "0.4", default-features = false }
embassy-nrf = { version = "0.1", default-features = false }
embassy-rp = { version = "0.1", default-features = false }
embassy-sync = { version = "0.5", default-features = false }
embassy-time = { version = "0.3", default-features = false }
embassy-usb = { version = "0.1", default-features = false }

linkme = { version = "0.3.21", features = ["used_linker"] }

riot-rs = { path = "src/riot-rs" }
riot-rs-rt = { path = "src/riot-rs-rt" }
riot-rs-runqueue = { path = "src/riot-rs-runqueue" }

riot-wrappers = { version = "^0.8", default-features = false, features = [
  "with_riot_rs",
] }

static_cell = { version = "2.0.0", features = [ "nightly" ] }
ld-memory = { version = "0.2.9" }
konst = { version = "0.3.8", default_features = false }
const_panic = { version = "0.2.8", default_features = false }

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"

[patch.crates-io]
# these have some patches to support riot.rs
riot-sys = { git = "https://github.com/kaspar030/rust-riot-sys", branch = "update_riot_rs_support" }
riot-wrappers = { git = "https://github.com/kaspar030/rust-riot-wrappers", branch = "add_riotrs_support" }
# these are listed so deps doesn't pull from crates.io
# (there are dummy crates so riot-wrappers / riot-sys compile while riot-rs has not published any crates)
riot-build = { path = "src/riot-build" }
riot-rs-core = { path = "src/riot-rs-core" }
riot-rs-runqueue = { path = "src/riot-rs-runqueue" }

# these are patched to work with critical-section
nrf51-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
nrf52840-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
nrf52832-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }

# riot-rs embassy fork
embassy-executor = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-executor-macros = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124"}
embassy-net = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-nrf = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-rp = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-time = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-sync = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
embassy-usb = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-230124" }
