#
# This file configures "criticalup", the Ferrocene qualified Rust toolchain.
#
manifest-version = 1

[products.ferrocene]
# First release to contain https://github.com/ferrocene/ferrocene/pull/1440.
release = "nightly-2025-04-30"
packages = [
  "rust-std-thumbv6m-none-eabi",
  "rust-std-thumbv7em-none-eabi",
  "rust-std-thumbv8m.main-none-eabi",
  "rust-std-${rustc-host}",
  "cargo-${rustc-host}",
  "clippy-${rustc-host}",
  "rustfmt-${rustc-host}",
  "llvm-tools-${rustc-host}",
  "rustc-${rustc-host}",
  "rust-src",
]
