[package]
name = "rp2040"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(context = "rp2040")'.dependencies]
riot-rs-embassy = { path = "../../riot-rs-embassy" }
riot-rs-rt = { path = "../../riot-rs-rt", features = ["rtt-target"] }
