[package]
name = "example-usb-serial"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["override-usb-config"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

[lints]
workspace = true
