[package]
name = "udp-echo"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["udp"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

[lints]
workspace = true
