[package]
name = "ariel-os-buildinfo"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ariel-os-utils = { workspace = true }

[lints]
workspace = true
