[package]
name = "ariel-os-buildinfo"
version = "0.2.0"
license.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ariel-os-utils = { workspace = true }
