[package]
name = "riot-rs-debug"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true, features = ["critical-section-single-core"] }
cortex-m-semihosting = { workspace = true, optional = true }
rtt-target = { version = "0.4.0", optional = true }

[target.'cfg(context = "esp")'.dependencies]
esp-println = { workspace = true, features = ["esp32c3", "log"] }
log = { version = "0.4.20" }

[features]
debug-console = []
