[package]
name = "riot-rs-storage"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
description = "RIOT-rs storage API"
license = "Apache-2.0 / MIT"

[lints]
workspace = true

[dependencies]
riot-rs-debug = { workspace = true }
arrayvec = { version = "0.7.4", default-features = false }
embassy-embedded-hal = { workspace = true }
embedded-storage-async = "0.4.1"
sequential-storage = { version = "2.0.0", git = "https://github.com/tweedegolf/sequential-storage", features = [
  "arrayvec",
], rev = "5f4fa19b8d366565aaadc1a8308d8901cbbf837e" }
serde = { version = "1.0.197", default-features = false }
postcard = { version = "1.0.8", features = ["postcard-derive"] }
