[default]
gdb.enabled = true

[default.rtt]
enabled = true

up_channels = [
  { channel = 0, format = "Defmt" },
  { channel = 1 },
]

tabs = [
    { up_channel = 0, name = "defmt including log" },
    { up_channel = 1, name = "Terminal" },
]
