[default]
gdb.enabled = true

[default.rtt]
enabled = true

up_channels = [
  { channel = 1, format = "Defmt", socket = "[::1]:1338" },
  { channel = 0 },
]

tabs = [
    { up_channel = 1, name = "defmt including log" },
    { up_channel = 0, name = "Terminal" },
]
