[package]
name = "ariel-os-macros"
version = "0.2.0"
license.workspace = true
edition.workspace = true
repository.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
enum-iterator = "2.1.0"
proc-macro-crate = "3.1.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.47", features = ["full"] }

[dev-dependencies]
heapless = { workspace = true }
ariel-os = { workspace = true, features = [
  "threading",
  "no-boards",
  "usb-ethernet",
  "network-config-override",
] }
trybuild = "1.0.89"

[lib]
proc-macro = true

[features]
_test = []
