[package]
name = "ariel-os-boards"
version = "0.2.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

[features]
# Allows to have no boards selected, useful to run platform-independent tooling
no-boards = []
