[package]
name = "ariel-os-sensor-stts22h"
# This crate is versioned separately from Ariel OS.
version = "0.1.0"
license.workspace = true
edition.workspace = true
# This crate's MSRV is decoupled from Ariel OS's.
rust-version = "1.85"
repository.workspace = true

[dependencies]
ariel-os-debug = { workspace = true }
ariel-os-embassy = { workspace = true }
ariel-os-hal = { workspace = true, features = ["i2c"] }
ariel-os-sensors = { workspace = true }
ariel-os-sensors-utils = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embedded-hal-async = { workspace = true }

[features]
_test = []

[lints]
workspace = true
