[package]
name = "riot-rs-coap"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
coapcore.path = "../lib/coapcore"
riot-rs-random.path = "../riot-rs-random"
riot-rs-embassy.path = "../riot-rs-embassy"

# actually patched with https://github.com/smoltcp-rs/smoltcp/pull/904 but
# patch.crates-io takes care of that
smoltcp = { version = "0.11", default-features = false }

embedded-nal-coap = "0.1.0-alpha.2"
coap-handler = "0.2.0"

# for the udp_nal mod
embedded-nal-async = "0.7"
embedded-io-async = "0.6.1"

[lints]
workspace = true

[features]
# all for udp_nal
default = ["proto-ipv4"] # shame
# actually embedded-nal features, we have to match them here while developing udp_nal in here
proto-ipv4 = ["smoltcp/proto-ipv4"]
proto-ipv6 = ["smoltcp/proto-ipv6"]
