[package]
name = "random"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
# not enabling riot-rs/hwrng even though it's currently needed -- laze takes
# care of that.
riot-rs = { path = "../../src/riot-rs", features = ["threading"] }
riot-rs-boards = { path = "../../src/riot-rs-boards" }

riot-rs-random = { version = "0.1.0", path = "../../src/riot-rs-random" }
rand = { version = "0.8.5", default-features = false }
