[package]
name = "lm3s6965evb"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[dependencies]
riot-rs-rt = { workspace = true, features = ["cortex-m-semihosting"] }
