[package]
name = "threading-multicore"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["core-affinity"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

[lints]
workspace = true
