//! Driver for the sensor used over I2C.

use ariel_os_sensors::{
    Category, Label, MeasurementUnit, Sensor,
    sensor::{
        Mode as SensorMode, ReadingChannel, ReadingChannels, ReadingError, ReadingResult,
        ReadingWaiter, Sample, Samples, SetModeError, State, TriggerMeasurementError,
    },
    signal::Signal as ReadingSignal,
};
use ariel_os_sensors_utils::AtomicState;
use embassy_sync::{
    blocking_mutex::raw::CriticalSectionRawMutex, mutex::Mutex, once_lock::OnceLock, signal::Signal,
};
use embassy_time::Timer;
use embedded_hal_async::i2c::{
    Error as _, ErrorKind as I2CErrorKind, I2c, NoAcknowledgeSource::Data,
};

#[cfg(feature = "no_runner")]
use embassy_futures::block_on;

// The I2C address is fixed
const I2C_ADDRESS: u8 = 0x38;

ariel_os_hal::define_peripherals!(
    /// Peripherals required by the sensor driver.
    Peripherals {}
);

/// Driver to use an SHT3X over I2C.
pub struct Aht20<I2C> {
    state: AtomicState,
    label: Option<&'static str>,
    i2c: OnceLock<Mutex<CriticalSectionRawMutex, I2C>>,
    #[cfg(not(feature = "no_runner"))]
    signaling: Signal<CriticalSectionRawMutex, ()>,
    reading: ReadingSignal<ReadingResult<Samples>>,
}

impl<I2C: I2c + Send> Aht20<I2C> {
    /// Creates an uninitialized driver.
    #[must_use]
    pub const fn new(label: Option<&'static str>) -> Self {
        Self {
            state: AtomicState::new(State::Uninitialized),
            label,
            i2c: OnceLock::new(),
            #[cfg(not(feature = "no_runner"))]
            signaling: Signal::new(),
            reading: ReadingSignal::new(),
        }
    }

    /// Initializes the driver.
    pub async fn init(
        &'static self,
        _peripherals: Peripherals,
        mut i2c_device: I2C,
    ) {
        if !self.i2c.is_set() {
            // The Datasheet says that the sensor takes at most 20ms to enter idle state
            Timer::after_millis(20).await;

            // Check for calibration status
            loop {
                // The read the status byte to check
                let mut buf = [0u8];
                if i2c_device.write_read(
                    I2C_ADDRESS,
                    &[crate::Command::ReadStatusReg as u8],
                    &mut buf,
                    ).await.is_err() {
                        return;
                }

                if buf[0] & crate::CALIBRATION_STATUS != 0 {
                    #[cfg(feature = "debug")]
                    ariel_os_debug::log::info!("Sensor is Calibrated");
                    break;
                }

                // If the byte is unset, send an initialize command
                // and wait for 10 ms. See section 5.4.1 of the datasheet
                if i2c_device.write(
                    I2C_ADDRESS,
                    &[
                        crate::Command::Initialize as u8,
                        crate::INITIALIZE_ARG_0,
                        crate::INITIALIZE_ARG_1,
                    ]
                ).await.is_err() {
                    return;
                }

                Timer::after_millis(10).await;
            }
            #[cfg(feature = "debug")]
            ariel_os_debug::log::info!("Setting up done");
            let _ = self.i2c.init(Mutex::new(i2c_device));

            self.state.set(State::Enabled);
        }
    }

    /// Soft resets the device.
    ///
    /// # Errors
    /// - When the I2C connection fails.
    async fn reset(&self) -> Result<(), ()> {
        let mut i2c = self.i2c.get().await.lock().await;
        i2c
            .write(
                I2C_ADDRESS,
                &[crate::Command::SoftReset as u8],
            )
            .await
            .map_err(|_| ())?;
        Ok(())
    }




    /// Reads the status register and return it as a u8.
    ///
    /// # Errors
    /// - When the I2C connection fails for any reason.
    ///
    pub async fn read_status(&'static self) -> Result<u8, ()> {
        let mut i2c = self.i2c.get().await.lock().await;

        // Read the status register
        let mut buf = [0u8];
        i2c.write_read(
            I2C_ADDRESS,
            &[crate::Command::ReadStatusReg as u8],
            &mut buf,
        )
        .await
        .map_err(|_| ())?;

        Ok(buf[0])
    }


    /// Listens for measurement requests generated by [`Aht20::trigger_measurement()`], and
    /// responds to them.
    /// This should be called before [`Aht20::wait_for_reading()`], as that method will otherwise
    /// not be able to respond to measurement requests from [`Aht20::trigger_measurement()`].
    ///
    /// # Note
    ///
    /// [`Aht20::init()`] needs to be called and `await`ed before calling this method.
    #[cfg(not(feature = "no_runner"))]
    pub async fn run(&'static self) -> ! {
        loop {
            self.signaling.wait().await;

            self.reading.signal(self.measure().await);
        }
    }

    /// Trigger a measurement and process the results.
    ///
    /// # Errors
    /// - When the I2C connection fails.
    /// - When the CRC of either the temperature or the relative humidity are incorrect.
    ///
    async fn measure(&'static self) -> ReadingResult<Samples> {
        let mut i2c = self.i2c.get().await.lock().await;

        #[cfg(feature = "debug")]
        ariel_os_debug::log::info!("Triggering Measurement");
        // Trigger a one-shot measurement.
        i2c.write(
            I2C_ADDRESS,
            &[
                crate::Command::TriggerMeasurement as u8,
                crate::MEASUREMENT_ARG_0,
                crate::MEASUREMENT_ARG_1,
            ]
        )
        .await
        .map_err(|_| ReadingError::SensorAccess)?;
        // Wait for at least 80 ms, see Section 5.4.3 of the Datasheet
        Timer::after_millis(80).await;
        #[cfg(feature = "debug")]
        ariel_os_debug::log::info!("Looping over status bit");
        let mut buf = [0u8];
        loop {
            match i2c.read(I2C_ADDRESS, &mut buf).await {
                // Busy
                Err(e) if e.kind() == I2CErrorKind::NoAcknowledge(Data) => {}
                Err(_) => {
                    return Err(ReadingError::SensorAccess);
                }
                Ok(()) => {
                    // Check if the busy bit of the status register is set to 1
                    if buf[0] & crate::BUSY_BIT == 0 {
                        break;
                    }
                }
            }
            // TODO: configuration
            Timer::after_millis(5).await;
        }
        // Now read |status|humi|humi|humi-temp|temp|temp|crc|
        let mut buf = [0u8; 7];
        i2c.read(I2C_ADDRESS, &mut buf).await.map_err(|_| ReadingError::SensorAccess)?;

        #[cfg(feature = "debug")]
        ariel_os_debug::log::info!("Checking the CRC");
        #[cfg(feature = "debug")]
        ariel_os_debug::log::info!("Data: {:?}, Expected CRC: {}", &buf[..6], buf[6]);
        if !crate::check_crc(&buf[0..6], buf[6]) {
            // FIXME: Use a better error type
            // return Err(ReadingError::SensorAccess);
            ariel_os_debug::log::info!("CRC check failed");

        }

        #[cfg(feature = "debug")]
        ariel_os_debug::log::info!("Converting raw values");
        let humidity = ((buf[1] as u32) << 12) + ((buf[2] as u32) << 4) + buf[3] as u32 / 16;
        let temperature = ((buf[3] as u32 % 16) << 16) + ((buf[4] as u32) << 8) + buf[5] as u32;

        // H = (Sh / 2^20) * 100 % see Section 6.1 of the Datasheet.
        // This naturally brings the resolution down the %.
        let humi = (humidity as i32 * 100) >> 20;

        // T = (St / 2^20) * 200 - 50 see Section 6.2 of the Datasheet.
        // We pre-multiply by 10 to keep the decimal digit
        let temp = ((temperature as i32 * 200 * 10) >> 20) - 500;

        let h_accuracy = crate::h_accuracy(humi);
        let sample_humi = Sample::new(humi, h_accuracy);

        let t_accuracy = crate::t_accuracy(temp);
        let sample_temp = Sample::new(temp, t_accuracy);

        let samples = Samples::from_2(self, [sample_humi, sample_temp]);

        Ok(samples)
    }
}

impl<I2C: I2c + Send> Sensor for Aht20<I2C> {
    fn trigger_measurement(&self) -> Result<(), TriggerMeasurementError> {
        self.reading.clear();

        match self.state.get() {
            State::Measuring => {}
            State::Enabled => {
                self.state.set(State::Measuring);
            }
            State::Uninitialized | State::Disabled | State::Sleeping => {
                return Err(TriggerMeasurementError::NonEnabled);
            }
        }

        #[cfg(not(feature = "no_runner"))]
        self.signaling.signal(());

        Ok(())
    }

    #[cfg(not(feature = "no_runner"))]
    fn wait_for_reading(&'static self) -> ReadingWaiter {
        match self.state.get() {
            State::Measuring => {
                self.state.set(State::Enabled);

                ReadingWaiter::new(self.reading.wait())
            }
            State::Enabled => ReadingWaiter::new_err(ReadingError::NotMeasuring),
            State::Uninitialized | State::Disabled | State::Sleeping => {
                ReadingWaiter::new_err(ReadingError::NonEnabled)
            }
        }
    }

    #[cfg(feature = "no_runner")]
    fn wait_for_reading(&'static self) -> ReadingWaiter {
        match self.state.get() {
            State::Measuring => {
                self.state.set(State::Enabled);
                self.reading.signal(block_on(self.measure()));
                ReadingWaiter::new(self.reading.wait())
            }
            State::Enabled => ReadingWaiter::new_err(ReadingError::NotMeasuring),
            State::Uninitialized | State::Disabled | State::Sleeping => {
                ReadingWaiter::new_err(ReadingError::NonEnabled)
            }
        }
    }

    fn set_mode(&self, mode: SensorMode) -> Result<State, SetModeError> {
        let new_state = self.state.set_mode(mode);

        if new_state == State::Uninitialized {
            Err(SetModeError::Uninitialized)
        } else {
            Ok(new_state)
        }
    }

    fn state(&self) -> State {
        self.state.get()
    }

    fn categories(&self) -> &'static [Category] {
        &[Category::RelativeHumidityTemperature]
    }

    fn reading_channels(&self) -> ReadingChannels {
        ReadingChannels::from([
            ReadingChannel::new(
                Label::RelativeHumidity,
                0,
                MeasurementUnit::PercentageRelativeHumidity,
            ),
            ReadingChannel::new(Label::Temperature, -1, MeasurementUnit::Celsius),
        ])
    }

    fn label(&self) -> Option<&'static str> {
        self.label
    }

    fn display_name(&self) -> Option<&'static str> {
        Some("humidity/temperature sensor")
    }

    fn part_number(&self) -> Option<&'static str> {
        Some(crate::PART_NUMBER)
    }

    fn version(&self) -> u8 {
        0
    }
}

#[cfg(feature = "nope")]
mod tests {
    use embedded_hal_async::i2c::{ErrorKind, Operation};

    use super::*;
    use crate::Command::SingleShotDisabledMedium;
    use crate::Command::SoftReset;
    use crate::calculate_crc;

    #[derive(Debug)]
    enum Error {}

    impl embedded_hal_async::i2c::Error for Error {
        fn kind(&self) -> ErrorKind {
            ErrorKind::Other
        }
    }

    #[derive(Default)]
    struct I2cDeviceMock {
        reading_count: usize,
        reading_status: bool,
    }

    impl embedded_hal_async::i2c::ErrorType for I2cDeviceMock {
        type Error = Error;
    }

    impl I2c for I2cDeviceMock {
        async fn transaction(
            &mut self,
            _address: embedded_hal_async::i2c::SevenBitAddress,
            operations: &mut [Operation<'_>],
        ) -> Result<(), Self::Error> {
            match operations {
                [Operation::Write(wbuf)] => match u16::from_be_bytes([wbuf[0], wbuf[1]]) {
                    command if command == SoftReset as u16 => {}
                    command if command == SingleShotDisabledMedium as u16 => {
                        self.reading_status = true;
                    }
                    _ => panic!("unknown acquisition command"),
                },
                [Operation::Read(rbuf)] => match self.reading_status {
                    true => {
                        // Provide different samples for consecutive readings.
                        let samples: (u16, u16) = match self.reading_count {
                            0 => (2500, 6390),  // T: -3832, RH: 975
                            1 => (1800, 60000), // T: -4019, RH: 9155
                            _ => panic!("too many readings"),
                        };
                        // Temperature
                        rbuf[0..2].copy_from_slice(&samples.0.to_be_bytes());
                        // Temperature CRC
                        rbuf[2] = calculate_crc(samples.0.to_be_bytes());
                        // Relative Humidity
                        rbuf[3..5].copy_from_slice(&samples.1.to_be_bytes());
                        // Temperature CRC
                        rbuf[5] = calculate_crc(samples.1.to_be_bytes());
                        self.reading_count += 1;
                        self.reading_status = false;
                    }
                    false => {
                        panic!("acquisition wasn't triggered beforehand")
                    }
                },
                _ => {}
            }

            Ok(())
        }
    }

    #[test]
    fn fetch_reading() {
        use ariel_os_sensors::{Reading, sensor::SampleMetadata};

        static SHT3X: Sht3x<I2cDeviceMock> = Sht3x::<I2cDeviceMock>::new(Some("label"));

        init_sensor(&SHT3X);

        embassy_futures::block_on(async {
            embassy_futures::select::select(SHT3X.run(), async {
                SHT3X.trigger_measurement().unwrap();

                let reading = SHT3X.wait_for_reading().await.unwrap();
                let [(t_channel, t_sample), (rh_channel, rh_sample)] =
                    reading.samples().collect::<Vec<(ReadingChannel, Sample)>>()[0..2]
                else {
                    unreachable!()
                };

                assert_eq!(t_channel.label(), Label::Temperature);
                assert_eq!(t_sample.value(), Ok(-3832));

                assert_eq!(rh_channel.label(), Label::RelativeHumidity);
                assert_eq!(rh_sample.value(), Ok(975));

                assert_eq!(
                    t_sample.metadata(),
                    SampleMetadata::SymmetricalError {
                        deviation: 40,
                        bias: 0,
                        scaling: -2,
                    }
                );

                assert_eq!(
                    rh_sample.metadata(),
                    SampleMetadata::SymmetricalError {
                        deviation: 250,
                        bias: 0,
                        scaling: -2,
                    }
                );

                SHT3X.trigger_measurement().unwrap();

                let reading = SHT3X.wait_for_reading().await.unwrap();
                let [(_t_channel, t_sample), (_rh_channel, rh_sample)] =
                    reading.samples().collect::<Vec<(ReadingChannel, Sample)>>()[0..2]
                else {
                    unreachable!()
                };
                assert_eq!(t_sample.value(), Ok(-4019));
                assert_eq!(
                    t_sample.metadata(),
                    SampleMetadata::SymmetricalError {
                        deviation: 75,
                        bias: 0,
                        scaling: -2,
                    }
                );

                assert_eq!(rh_sample.value(), Ok(9155));
                assert_eq!(
                    rh_sample.metadata(),
                    SampleMetadata::SymmetricalError {
                        deviation: 35,
                        bias: 0,
                        scaling: -1,
                    }
                );
            })
            .await;
        });
    }

    #[test]
    fn awaited_before_triggered() {
        static SHT3X: Sht3x<I2cDeviceMock> = Sht3x::<I2cDeviceMock>::new(Some("label"));

        init_sensor(&SHT3X);

        embassy_futures::block_on(async {
            embassy_futures::select::select(SHT3X.run(), async {
                assert!(matches!(
                    SHT3X.wait_for_reading().await,
                    Err(ReadingError::NotMeasuring)
                ));
            })
            .await
        });
    }

    #[test]
    fn cleared_when_double_triggered() {
        use ariel_os_sensors::Reading;

        static SHT3X: Sht3x<I2cDeviceMock> = Sht3x::<I2cDeviceMock>::new(Some("label"));

        init_sensor(&SHT3X);

        embassy_futures::block_on(async {
            embassy_futures::select::select(SHT3X.run(), async {
                SHT3X.trigger_measurement().unwrap();

                // The mock reading counter does not get incremented otherwise.
                embassy_futures::yield_now().await;

                // Should clear the first reading.
                SHT3X.trigger_measurement().unwrap();

                let reading = SHT3X.wait_for_reading().await.unwrap();
                let [(_t_channel, t_sample), (_rh_channel, rh_sample)] =
                    reading.samples().collect::<Vec<(ReadingChannel, Sample)>>()[0..2]
                else {
                    unreachable!()
                };

                // Should return the second reading.
                assert_eq!(t_sample.value(), Ok(-4019));
                assert_eq!(rh_sample.value(), Ok(9155));
            })
            .await
        });
    }

    #[test]
    fn multiple_waiters() {
        use ReadingError::NotMeasuring;

        static SHT3X: Sht3x<I2cDeviceMock> = Sht3x::<I2cDeviceMock>::new(Some("label"));

        init_sensor(&SHT3X);

        embassy_futures::block_on(async {
            embassy_futures::select::select(SHT3X.run(), async {
                SHT3X.trigger_measurement().unwrap();

                let join =
                    embassy_futures::join::join(SHT3X.wait_for_reading(), SHT3X.wait_for_reading())
                        .await;
                // Exactly one of them must be `Ok` and the other `Err`.
                assert!(matches!(
                    join,
                    (Ok(_), Err(NotMeasuring)) | (Err(NotMeasuring), Ok(_))
                ));

                SHT3X.trigger_measurement().unwrap();

                let join = embassy_futures::join::join3(
                    SHT3X.wait_for_reading(),
                    SHT3X.wait_for_reading(),
                    SHT3X.wait_for_reading(),
                )
                .await;
                // Exactly one of them must be `Ok` and the others `Err`.
                assert!(matches!(
                    join,
                    (Ok(_), Err(NotMeasuring), Err(NotMeasuring))
                        | (Err(NotMeasuring), Ok(_), Err(NotMeasuring))
                        | (Err(NotMeasuring), Err(NotMeasuring), Ok(_))
                ));
            })
            .await
        });
    }

    #[test]
    fn cancel_safety() {
        use ariel_os_sensors::Reading;

        static SHT3X: Sht3x<I2cDeviceMock> = Sht3x::<I2cDeviceMock>::new(Some("label"));

        init_sensor(&SHT3X);

        embassy_futures::block_on(async {
            embassy_futures::select::select(SHT3X.run(), async {
                SHT3X.trigger_measurement().unwrap();

                // The mock reading counter does not get incremented otherwise.
                embassy_futures::yield_now().await;

                let waiter = SHT3X.wait_for_reading();
                // Cancel the Future.
                drop(waiter);

                SHT3X.trigger_measurement().unwrap();

                let reading = SHT3X.wait_for_reading().await.unwrap();
                let [(_t_channel, t_sample), (_rh_channel, rh_sample)] =
                    reading.samples().collect::<Vec<(ReadingChannel, Sample)>>()[0..2]
                else {
                    unreachable!()
                };

                // Should return the second reading.
                assert_eq!(t_sample.value(), Ok(-4019));
                assert_eq!(rh_sample.value(), Ok(9155));
            })
            .await
        });
    }

    fn init_sensor(sht3x: &'static Sht3x<I2cDeviceMock>) {
        embassy_futures::block_on(async {
            let peripherals = Peripherals {};
            let i2c_device = I2cDeviceMock::default();
            let config = Config::default();

            sht3x.init(peripherals, i2c_device, config).await;
        });
    }
}
