name: PR dependencies

on:
  pull_request_target:
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [synchronize]
  merge_group:

jobs:
  check_dependencies:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    name: Check
    steps:
    - uses: gregsdennis/dependencies-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
