name: hax

# on:
#   pull_request:
#   push:

jobs:
  hax:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: ⤵ Install and configure hax
        uses: hacspec/hax-actions@main
        with:
          # pin hax to known-working
          hax_reference: cc29a3f8c0eee80a1682be78cb3b0447a0257d5b

      - name: 🏃 Extract `ariel-os-runqueue`
        working-directory: ./src/ariel-os-runqueue
        run: |
          rm -f proofs/fstar/extraction/*.fst*
          cargo hax into fstar

      - name: 🏃 Lax check `ariel-os-runqueue`
        working-directory: ./src/ariel-os-runqueue/proofs/fstar/extraction
        run: OTHERFLAGS="--lax" make
